name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build . --file Dockerfile --tag yohanshimalka9999/cicd:my-image-name-$IMAGE_TAG
        docker push yohanshimalka9999/cicd:my-image-name-$IMAGE_TAG
